version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: georgia-connects-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: georgia_connects_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5433:5432"
    networks:
      - georgia-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: georgia-connects-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - georgia-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # pgAdmin (Optional - Database Management Tool)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: georgia-connects-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@georgia-connects-hub.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - georgia-network
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres_data:
    name: georgia_connects_postgres_data
    driver: local
  redis_data:
    name: georgia_connects_redis_data
    driver: local
  pgadmin_data:
    name: georgia_connects_pgadmin_data
    driver: local

networks:
  georgia-network:
    name: georgia_connects_network
    driver: bridge
